app/projects/urls.py
from django.urls import path

from .views import (
    ProjectListView,
    ProjectDetailView,
    ProjectCreateView,
    ProjectUpdateView,
    ProjectDeleteView,
)

app_name = 'projects'

urlpatterns = [
    path('', ProjectListView.as_view(), name='all-projects-list'),
    path('create/', ProjectCreateView.as_view(), name='project-create'),
    path('<pk>/', ProjectDetailView.as_view(), name='project-details'),
    path('<pk>/update/', ProjectUpdateView.as_view(), name='project-update'),
    path('<pk>/delete/', ProjectDeleteView.as_view(), name='project-delete'),
]

app/skillhub/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('projects.urls')),
]

app/projects/models.py
from datetime import datetime

from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse

from skillhub.models import BaseModel


class Project(BaseModel):
    """
    Project class is the leading entity of Projects app
    """
    title = models.CharField(max_length=100)
    subtitle = models.CharField(max_length=100)
    description = models.TextField(null=True, blank=True)
    
    start_date = models.DateTimeField(null=True, blank=True)
    end_date = models.DateTimeField(null=True, blank=True)
    due_date = models.DateTimeField(null=True, blank=True)

    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='projects')

    def __str__(self):
        return f"@{self.user.username}/{self.title}"
    
    def isDelayed(self):
        return True if datetime.now() > self.due_date else False
    
    def get_absolute_url(self):
        return reverse("projects:project-details", kwargs={"pk": self.pk})
    

app/skillhub/models.py
from django.db import models


class BaseModel(models.Model):
    """
    BaseModel abstract class with primitive fields
    """
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True

app/projects/forms.py
from django.forms import ModelForm

from .models import Project


class ProjectForm(ModelForm):
    """
    Form class for creating and editing a Project
    """
    class Meta:
        model = Project
        fields = ['title', 'subtitle', 'description', 'due_date', 'user']

app/projects/views.py
from django.shortcuts import render
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import (
    CreateView,
    UpdateView,
    DeleteView,
)
from django.urls import reverse_lazy
from django.urls import reverse

from .models import Project


class ProjectListView(ListView):
    """
    Listing all the projects in database
    """
    model = Project
    template_name = 'project_list.html'


class ProjectDetailView(DetailView):
    """
    Printing the details of a single project
    """
    model = Project
    template_name = 'project_details.html'


class ProjectCreateView(CreateView):
    """
    Creating a new project in the system
    """
    model = Project
    template_name = 'project_create.html'
    fields = ('title', 'subtitle', 'description', 'due_date', 'user')


class ProjectUpdateView(UpdateView):
    """
    Updating an existing project in the system
    """
    model = Project
    template_name = 'project_update.html'
    fields = ('subtitle', 'description')


class ProjectDeleteView(DeleteView):
    """
    Deleting an existing project in the system
    """
    model = Project
    template_name = 'project_details.html'
    success_url = reverse_lazy('projects:all-projects-list')

app/projects/templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">

    <title>SkillHub</title>
  </head>
  <body>
    
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand" href="#">SkillHub</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link" href="#">Projects</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Requests</a>
                </li>
            </ul>
            <ul class="navbar-nav ml-auto">
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    {% if request.user.is_authenticated %}
                    {{ request.user.username }}
                    {% else %}
                    Guest
                    {% endif %}
                    </a>
                    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item" href="#">Your profile</a>
                    <a class="dropdown-item" href="#">Your projects</a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="#">Sign out</a>
                    </div>
                </li>
            </ul>
        </div>
    </nav>

    {% block contents %}
    {% endblock contents %}

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>

  </body>
</html>

app/projects/templates/project_create.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block contents %}

<h4>Create new project</h4>

<form method="POST">
    {% csrf_token %}
    {{ form|crispy }}
    <button type="submit" class="btn btn-primary">Create</button>
</form>

{% endblock contents %}

app/projects/templates/project_details.html
{% extends 'base.html' %}

{% block contents %}

<div class="card">
  <div class="card-body">
    <h5 class="card-title">{{ project.title }}</h5>
    <h6 class="card-subtitle mb-2 text-muted">{{ project.subtitle }}</h6>
    <p class="card-text">{{ project.description }}</p>
    <a href="{% url 'projects:project-update' pk=project.pk %}" class="btn btn-primary">Edit</a>
    <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#confirmDeleteModal">
      Delete
    </button>
  </div>
</div>

<div class="modal fade" id="confirmDeleteModal" tabindex="-1" aria-labelledby="confirmDeleteModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="confirmDeleteModalLabel">Modal title</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        You will lose your data and progress, are you sure ?
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">No, take me back</button>
        <form method="post" action="{% url 'projects:project-delete' pk=project.pk %}">
          {% csrf_token %}
          <input type="submit" class="btn btn-danger" value="Yes, delete">
        </form>
      </div>
    </div>
  </div>
</div>

{% endblock contents %}

app/projects/templates/project_list.html
{% extends 'base.html' %}

{% block contents %}

{% for project in object_list %}
<div class="card">
  <div class="card-body">
    <h5 class="card-title">{{ project.title }}</h5>
    <h6 class="card-subtitle mb-2 text-muted">{{ project.subtitle }}</h6>
    <p class="card-text">{{ project.description }}</p>
    <a href="{% url 'projects:project-details' pk=project.pk %}" class="btn btn-primary">Open details</a>
  </div>
</div>
{% empty %}
<h4>No projects found</h4>
{% endfor %}

{% endblock contents %}

app/projects/templates/project_update.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block contents %}

<h4>Update project</h4>

<form method="POST">
    {% csrf_token %}
    {{ form|crispy }}
    <button type="submit" class="btn btn-primary">Update</button>
</form>

{% endblock contents %}